### ISSUE TITLE
Comma missing

### ISSUE THREAD

**Issue by belgoros** [dulmandakh/ember-cli-foundation-6#1]
In the provided bock:
```
  let app = new EmberApp(defaults, {
    'ember-cli-foundation-6': {
      css: true
      js: true
    }
```
a comma is missing after `css: true` what make Ember fail to start:
```
Could not require 'ember-cli-build.js': Unexpected identifier
/Users/XXX/ember-cli-build.js:10
      js: true

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/Serguei/projects/ruby/ember-foundation/node_modules/ember-cli/lib/utilities/find-build-file.js:18:17)
```
Even after adding the comma like that:
```
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    'ember-cli-foundation-6': {
      css: true,
      js: true
    }
  });
```
there are no Foundation CSS loaded whan checking it in the Chrome inspector :(. Any tips ? Thank you.
Here is my Ember config:
```
➜  ember-foundation git:(master) ✗ ember -v
ember-cli: 2.16.2
node: 8.9.1
os: darwin x64
```

**Comment by belgoros** [comment]
The css were loaded and worked as needed after (sorry, my bad) running:
```
ember install ember-cli-foundation-6
```
But the comme should be added nevertheless.

**Comment by dulmandakh** [comment]
thank you, fixed
